pub mod app;
pub mod app_state;
pub mod audio_model;
pub mod config;
#[cfg(feature = "gtk-ui")]
pub mod e2e;
#[cfg(feature = "egui-ui")]
#[path = "ui/egui/mod.rs"]
pub mod egui_frontend;
pub mod equalizer;
pub mod mpris;
pub mod playback;
pub mod player;
pub mod playlist;
pub mod render;
pub mod session;
pub mod skin;
#[cfg(feature = "gtk-ui")]
pub mod skineditor;
pub mod socket_control;
#[cfg(feature = "gtk-ui")]
pub mod ui;
